### PR TITLE
Added temporary header and footer

### PR DESCRIPTION
**Pull request by JammiM**
Added a simple header and footer section.

### CODE REVIEW

**Comment by JammiM** [comment]
I have added a simple project page for people to display links to their personal projects.
More people can add their personal projects at a later date.

**Comment by Dean-Coakley** [comment]
@JammiM Maybe there should be a "Owner/Developer(s)" section for each entry? What do you think?

Nit: Empty line on line 38

**Comment by davej** [comment]
On holidays at the moment. I'll review when back (early June). Thanks 👍

**Comment by Dean-Coakley** [comment]
@davej Can we get this reviewed/merged?

**Comment by davej** [comment]
@JammiM @Dean-Coakley Can we actually add pages for the links (or remove the links altogether), I don't like having links that go nowhere.

Also, we should put something in the footer. Here's the description from meetup.com maybe it will do:

> Monthly meet-up for Corkonians to hang out and discuss all things JavaScript. This is just a bit of an informal chat with no speaker/presentation format but if you're working on something cool then feel free show it off! JS on the backend, JS on the frontend, interested beginners, and long-time pros. All are welcome. Come, hang out, and lets talk JS.

**Review by JammiM — COMMENTED** [review]
I added links to two other pages "Projects" a page for coders to display links to projects that there working on. "Learning Resources" a page providing links to tutorials pertaining to development.

**Comment by davej** [comment]
Ok, cool, I will merge. I'll comment out the links for the moment until the pages have content in them.

Thanks 👍

**Pull request merged**
