### PR TITLE
Clickable meetup title and Directions

### PR DESCRIPTION
**Pull request by Dean-Coakley**
Made the title link to the event on meetup.com

Added directions link.
EDIT: Changed to search with venue name instead of innaccurate longitude and latitude.

Maybe you'd prefer an embedded map or for it to be laid out differently so let me know. :smile:

### CODE REVIEW

**Comment by davej** [comment]
Cool. Won't get to look into this until the weekend. I'll get back to you then.

**Comment by Dean-Coakley** [comment]
@davej Maybe you can take a quick look today/soon?

**Comment by davej** [comment]
Sorry, was very busy this week.

This looks perfect, I'll merge.

**Comment by davej** [comment]
Some irregularities with indentation. I'll fix it directly on the master brach though.

**Pull request merged**
